src/models.py
from flask_sqlalchemy import SQLAlchemy
from flask_security import UserMixin, RoleMixin


db = SQLAlchemy()


roles_users = db.Table('roles_users',
                       db.Column('user_id', db.Integer(), db.ForeignKey('user.id')),
                       db.Column('role_id', db.Integer(), db.ForeignKey('role.id')))


class User(db.Model, UserMixin):
    """A user.

    See the Flask-Security_ documentation for more information.

    _Flask-Security: https://pythonhosted.org/Flask-Security/index.html
    """ 
    id = db.Column(db.Integer(), primary_key=True)
    email = db.Column(db.String(255), nullable=False)
    password = db.Column(db.String(255), nullable=False)
    active = db.Column(db.Boolean, nullable=False)
    roles = db.relationship("Role", secondary="roles_users",
                            backref=db.backref("users", lazy="dynamic"))


class Role(db.Model, RoleMixin):
    """User roles.

    See the Flask-Security_ documentation for more information.

    _Flask-Security: https://pythonhosted.org/Flask-Security/index.html
    """
    id = db.Column(db.Integer(), primary_key=True)
    name = db.Column(db.Unicode(80), unique=True)
    description = db.Column(db.Unicode(255))


class Story(db.Model):
    """An audio story.

    The number is explicitly specified because it may be printed on some
    surface, and is used for sorting for the audio prompt.
    To ease changes, the prompt is stored as text and spoken aloud by TTS
    (text-to-speech).

    ``last_accessed`` is left as nullable because we cannot always give it a
    sensible value: newly created stories have never been accessed.
    """
    number = db.Column(db.Integer(), nullable=False, unique=True, primary_key=True)
    prompt = db.Column(db.Text(), nullable=False)
    name = db.Column(db.Text(), nullable=False)
    filename = db.Column(db.Text(), nullable=False)
    num_listens = db.Column(db.Integer(), nullable=False, default=0)
    last_accessed = db.Column(db.DateTime())

src/__init__.py
import flask
from flask_migrate import Migrate
from flask_wtf import CSRFProtect

def create_app(test_config=None):
    app = flask.Flask("src")
    if test_config is None:
        app.config.from_pyfile("config.py", silent=False)
    else:
        app.config.from_mapping(test_config)

    csrf = CSRFProtect(app)
    from .views import views
    from .controllers import controllers
    from .phone_interface import webhooks
    csrf.exempt(webhooks)
    app.register_blueprint(views)
    app.register_blueprint(controllers, url_prefix="/api")
    app.register_blueprint(webhooks, url_prefix="/voice")
    from .models import db
    db.init_app(app)
    migrate = Migrate(app, db)
    from .login import security, user_datastore
    security.init_app(app, user_datastore)
    return app

app = create_app()

src/controllers.py
from flask import Blueprint, current_app, flash, redirect, request, url_for
from flask_security import login_required
from sqlalchemy.orm.exc import NoResultFound


from .models import db, Story


import logging
from pathlib import Path
import sys
import traceback


controllers = Blueprint("controllers", __name__)


@controllers.route("/stories/create", methods=["POST"])
def create_story():
    all_fields_present = True
    if "name" not in request.form or request.form["name"].strip() == "":
        flash("Please provide a name for this story.", "error")
        all_fields_present = False
    if "prompt" not in request.form or request.form["prompt"].strip() == "":
        flash("Please provide a prompt for this story.", "error")
        all_fields_present = False
    if "number" not in request.form or request.form["number"].strip() == "":
        flash("Please enter a number for this story.", "error")
        all_fields_present = False
    if "audio_file" not in request.files:
        flash("Please provide an audio file for this story.", "error")
        all_fields_present = False

    if all_fields_present:
        name, prompt, number = map(lambda f: request.form[f].strip(), ["name", "prompt", "number"])

        try:
            Story.query.filter(Story.number == int(number)).one()
            flash("Story number must be unique.", "error")
        except NoResultFound:
            audio_file = request.files["audio_file"]
            filename = number + ".mp3"
            path = str(Path(current_app.config["STORY_FILE_DIRECTORY"]) / filename)
            db.session.add(Story(number=int(number), prompt=prompt, name=name, filename=filename))
            try:
                audio_file.save(path)
                db.session.commit()
                flash("Added new story.", "success")
            except OSError as e:
                raise e
                flash("Unable to save story audio file.", "error")
                logging.error("Problem saving audio file to disk: {}".format(e))
                db.session.rollback()
            except Exception as e:
                flash("Internal server error.", "error")
                logging.error("Problem creating new story: {}".format(e))

    return redirect(url_for("views.manage_stories"))



@controllers.route("/stories/modify/<int:number>", methods=["POST"])
def modify_story(number):
    if "name" not in request.form or request.form["name"] == "":
        flash("Story name must not be blank.", "error")
    elif "prompt" not in request.form or request.form["prompt"] == "":
        flash("Story prompt must not be blank.", "error")
    else:
        try:
            story = Story.query.filter(Story.number == number).one()
            story.name = request.form["name"]
            story.prompt = request.form["prompt"]
            db.session.commit()
            flash("Saved changes.", "success")
        except NoResultFound:
            flash("No such story exists.", "error")
        except Exception as e:
            logging.error("Exception while attempting to modify story: {}".format(e))
            db.session.rollback()
            flash("Internal database error.", "error")
    return redirect(url_for("views.manage_stories"))


@controllers.route("/stories/delete/<int:number>", methods=["POST"])
def delete_story(number):
    try:
        story = Story.query.filter(Story.number == number).one()
        file_path = Path(current_app.config["STORY_FILE_DIRECTORY"]) / story.filename
        db.session.delete(story)
        db.session.commit()
        file_path.unlink()
        flash("Removed story {}".format(number), "success")
    except NoResultFound:
        flash("No story with that number exists.", "error")
    except (OSError, Exception) as e:
        flash("Internal server error.", "error")
        logging.error("Unable to delete story: {}".format(e))
    return redirect(url_for("views.manage_stories"))

src/views.py
from flask import Blueprint, flash, render_template, url_for
from flask_security import login_required


from .models import db, Story


views = Blueprint("views", __name__, template_folder="templates")


@views.route("/")
@login_required
def index():
    return "Hello world"


@views.route("/manage_stories")
@login_required
def manage_stories():
    all_stories = Story.query.order_by(Story.number).all()
    return render_template("manage_stories.html", stories=all_stories)

src/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='style.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='tachyons.min.css') }}">
    <script type="text/javascript">
    function hideMessage(messageSelector) {
      let el = document.querySelector(messageSelector);
      if (el) {
        el.style.display = "none";
      }
    }
    </script>
  </head>
  <body class="flex flex-column items-center">
    <header class="flex flex-column items-center w-100">
        {% with messages = get_flashed_messages(with_categories=true) %}
          {% if messages %}
            {% for category, message in messages %}
              <div id="message-{{ loop.index }}"class="message message-{{ category }} mt2 br3 flex items-center">
                <span>{{ message }}</span>
                <span class="ml-auto f3 dim pointer" aria-label="Close"
                      onclick="hideMessage('#message-{{ loop.index }}')">
                  ×
                </span>
              </div>
            {% endfor %}
          {% endif %}
        {% endwith %}
    </header>
    <main>
    {% block content %}
    {% endblock %}
    </main>
  </body>
</html>

src/templates/index.html
{% extends "base.html" %}

<!-- TODO: Add header section to base, add header here. -->

{% block content %}
<h1>Walkstops Lower Haight</h1>

{% endblock %}

src/templates/manage_stories.html
{% extends "base.html" %}

{% block content %}
<section>
  <h1>Modify Existing Stories</h1>
  {% if stories %}
    <ul class="ph0 story-list">
      {% for story in stories %}
      <li class="mv4 mh2 flex justify-between">
        <form method="POST"
              action="{{ url_for('controllers.modify_story', number=story.number) }}"
              class="flex items-center mr6">
          <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
          <fieldset class="story-details mr4">
            <legend>Story {{ story.number }}</legend>
            <label for="story-{{ story.number }}-name" class="ml-auto">
              Name
            </label>
            <input id="story-{{ story.number }}-name" name="name"
                   class="story-details-field"
                   type="text" pattern="^.*[^\s]+.*$"
                   title="At least one non-whitespace character." required value="{{ story.name }}">
            <label for="story-{{ story.number }}-prompt" class="ml-auto">
              Prompt
            </label>
            <input id="story-{{ story.number }}-prompt" name="prompt"
                   class="story-details-field"
                   type="text" pattern="^.*[^\s]+.*$"
                   title="At least one non-whitespace character." 
                   size="30" required value="{{ story.prompt }}">
          </fieldset>
          <input type="submit" value="Save Changes">
        </form>
        <form method="POST" action="{{ url_for('controllers.delete_story', number=story.number) }}"
              class="flex items-center">
          <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
          <input type="submit" value="Delete" class="bg-red white bn br2 ph3 pv2 grow pointer">
        </form>
      </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>There are currently no stories available.</p>
  {% endif %}
</section>

<section>
  <h1>Create New Story</h1>
  <form method="POST" action="{{ url_for('controllers.create_story') }}" enctype="multipart/form-data">
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
    <div class="story-details">
      <label for="new-story-name" class="ml-auto">
        Name
      </label>
      <input id="new-story-name" name="name" type="text" pattern="^.*[^\s]+.*$"
             class="story-details-field"
             title="At least one non-whitespace character." required>
      <label for="new-story-prompt" class="ml-auto">
        Prompt
      </label>
      <input id="new-story-prompt" name="prompt" type="text" pattern="^.*[^\s]+.*$"
             class="story-details-field"
             size="30"
             title="At least one non-whitespace character." required>
      <label for="new-story-number" class="ml-auto">
        Number
      </label>
      <input id="new-story-number" name="number" type="number"
             class="story-details-field"
             required min="0">
      <label for="new-story-audio" class="ml-auto">
        Audio File (MP3 only)
      </label>
      <input id="new-story-audio" name="audio_file" type="file" accept="audio/mpeg" required>
    </div>
    <input type="submit" value="Create">
  </form>
</section>
{% endblock %}